<style>
.qb-design{--qb-bg:#f4f7fc;--qb-card:#fff;--qb-card-2:#f8faff;--qb-border:#d6e1f0;--qb-text:#142540;--qb-muted:#617798;--qb-blue:#1769ed;--qb-blue-soft:#e9f1ff;--qb-green:#087e55;--qb-green-soft:#e5f8ee;--qb-amber:#a76600;--qb-amber-soft:#fff4db;--qb-red:#c33d53;--qb-purple:#6555c9;color:var(--qb-text)}
.dark .qb-design{--qb-bg:#07152c;--qb-card:#0d203c;--qb-card-2:#0a1b34;--qb-border:#29476c;--qb-text:#f4f7ff;--qb-muted:#9eb7da;--qb-blue:#3988ff;--qb-blue-soft:#102e5c;--qb-green:#24d996;--qb-green-soft:#083a35;--qb-amber:#ffbc49;--qb-amber-soft:#4d310f;--qb-red:#fb5d75;--qb-purple:#8e82fb}
.qb-design.fi-page{background:var(--qb-bg);border-radius:16px;padding:24px;min-height:100vh;max-width:none!important}
.qb-design .fi-header{align-items:center;gap:20px;margin-bottom:24px}
.qb-design .fi-header-heading{font-size:clamp(2rem,3vw,3rem);font-weight:800;letter-spacing:-.03em;line-height:1.15;color:var(--qb-text)}
.qb-design .fi-header-subheading{font-size:1rem;color:var(--qb-muted);margin-top:8px}
.qb-design .fi-header-actions{gap:10px;flex-wrap:wrap}
.qb-design .fi-header-actions .fi-btn{min-height:44px;border-radius:10px;padding-inline:16px;box-shadow:none;font-weight:650}
.qb-design .fi-header-actions .fi-btn:not(.fi-color-primary){background:var(--qb-card);border:1px solid var(--qb-border);color:var(--qb-text)}
.qb-design .fi-header-actions .fi-btn.fi-color-primary{background:#216df3;color:white}
.qb-canvas{display:grid;gap:18px;direction:inherit}
.qb-card{background:linear-gradient(125deg,var(--qb-card),var(--qb-card-2));border:1px solid var(--qb-border);border-radius:14px;box-shadow:0 12px 32px rgba(0,7,25,.08);min-width:0}
.dark .qb-card{box-shadow:0 12px 32px rgba(0,0,0,.12)}
.qb-section{padding:20px}
.qb-section-head{display:flex;align-items:flex-start;gap:12px;margin-bottom:18px;min-width:0}
.qb-section-head h2{font-size:1.22rem;font-weight:750;line-height:1.35;margin:0;color:var(--qb-text)}
.qb-section-head p{font-size:.84rem;color:var(--qb-muted);margin:5px 0 0;line-height:1.5}
.qb-icon{width:40px;height:40px;flex:none;display:inline-flex;align-items:center;justify-content:center;border-radius:9px;color:var(--qb-blue);background:var(--qb-blue-soft);border:1px solid color-mix(in srgb,var(--qb-blue) 37%,transparent)}
.qb-icon svg{width:23px;height:23px}
.qb-icon--green{color:var(--qb-green);background:var(--qb-green-soft);border-color:color-mix(in srgb,var(--qb-green) 42%,transparent)}
.qb-icon--amber{color:var(--qb-amber);background:var(--qb-amber-soft);border-color:color-mix(in srgb,var(--qb-amber) 42%,transparent)}
.qb-icon--purple{color:var(--qb-purple);background:color-mix(in srgb,var(--qb-purple) 17%,var(--qb-card));border-color:color-mix(in srgb,var(--qb-purple) 44%,transparent)}
.qb-icon--muted{color:var(--qb-muted);background:var(--qb-card-2);border-color:var(--qb-border)}
.qb-pill{display:inline-flex;align-items:center;gap:5px;border:1px solid currentColor;border-radius:7px;padding:4px 9px;font-size:.76rem;font-weight:700;line-height:1.15;white-space:nowrap}
.qb-pill--green{color:var(--qb-green);background:var(--qb-green-soft)}
.qb-pill--amber{color:var(--qb-amber);background:var(--qb-amber-soft)}
.qb-pill--red{color:var(--qb-red);background:color-mix(in srgb,var(--qb-red) 13%,var(--qb-card))}
.qb-pill--gray{color:var(--qb-muted);background:var(--qb-card-2)}
.qb-hero{min-height:205px;padding:22px 26px;display:grid;grid-template-columns:minmax(0,1fr) 200px;align-items:center;gap:24px;overflow:hidden}
.qb-hero-art{grid-column:2;grid-row:1}.qb-hero-main{grid-column:1;grid-row:1}
.qb-hero--amber{border-color:color-mix(in srgb,var(--qb-amber) 70%,var(--qb-border));background:radial-gradient(circle at 9% 65%,color-mix(in srgb,var(--qb-amber) 24%,transparent),transparent 28%),linear-gradient(112deg,color-mix(in srgb,var(--qb-amber) 9%,var(--qb-card)),var(--qb-card-2) 70%)}
.qb-hero--green{border-color:color-mix(in srgb,var(--qb-green) 75%,var(--qb-border));background:radial-gradient(circle at 9% 60%,color-mix(in srgb,var(--qb-green) 23%,transparent),transparent 30%),linear-gradient(112deg,color-mix(in srgb,var(--qb-green) 9%,var(--qb-card)),var(--qb-card-2) 72%)}
.qb-hero-art{height:150px;display:flex;align-items:center;justify-content:center;position:relative;color:var(--qb-amber)}
.qb-hero-art:before,.qb-hero-art:after{content:"";position:absolute;inset:auto 10px 5px;border:1px solid currentColor;border-radius:50%;height:38px;opacity:.22}
.qb-hero-art:after{inset:auto 32px 14px;height:25px;opacity:.15}
.qb-hero-art svg{width:94px;height:94px;stroke-width:1.25;filter:drop-shadow(0 0 18px currentColor);z-index:1}
.qb-hero--green .qb-hero-art{color:var(--qb-green)}
.qb-hero-main{min-width:0}
.qb-hero-heading{display:flex;align-items:center;flex-wrap:wrap;gap:12px}
.qb-hero-heading h2{font-size:1.45rem;font-weight:800;margin:0;line-height:1.25;color:var(--qb-text)}
.qb-hero-main>p{color:var(--qb-muted);font-size:.95rem;line-height:1.6;margin:10px 0 0}
.qb-hero-foot{border-top:1px solid color-mix(in srgb,var(--qb-amber) 24%,var(--qb-border));margin-top:20px;padding-top:14px;color:var(--qb-muted);font-size:.86rem;display:flex;align-items:center;gap:8px}
.qb-hero-foot svg{width:19px;height:19px}
.qb-health .qb-hero{grid-template-columns:170px minmax(0,1fr) 180px;min-height:160px}.qb-health .qb-hero-art{grid-column:3}.qb-health .qb-hero-main{grid-column:2}.qb-health-rail{grid-column:1;grid-row:1;border-inline-end:1px solid var(--qb-border);padding-inline-end:18px;display:grid;gap:10px}.qb-health-rail>div{display:flex;gap:9px;align-items:flex-start;border-bottom:1px solid var(--qb-border);padding-bottom:9px;font-size:.8rem}.qb-health-rail>div:last-child{border:0;padding:0}.qb-health-rail svg{width:20px;height:20px;color:var(--qb-blue);flex:none}.qb-health-rail span{display:grid;gap:4px}.qb-health-rail bdi,.qb-health-rail small{font-size:.75rem;color:var(--qb-muted)}
.qb-summary-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}
.qb-summary-item{border:1px solid var(--qb-border);border-radius:12px;padding:16px;display:flex;align-items:center;gap:16px;min-width:0;background:color-mix(in srgb,var(--qb-card-2) 66%,transparent);min-height:105px}
.qb-summary-item>div:last-child{min-width:0}
.qb-summary-item h3{font-size:1rem;font-weight:700;margin:0 0 8px;color:var(--qb-text)}
.qb-summary-item p{font-size:.88rem;color:var(--qb-muted);margin:0}
.qb-columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;align-items:stretch}
.qb-empty{min-height:104px;border:1px dashed var(--qb-border);border-radius:12px;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:18px;gap:4px;background:color-mix(in srgb,var(--qb-card-2) 48%,transparent)}
.qb-empty svg{width:30px;height:30px;color:var(--qb-muted);margin-bottom:5px;opacity:.7}
.qb-empty strong{font-size:.93rem;color:var(--qb-text)}
.qb-empty span{font-size:.82rem;color:var(--qb-muted)}
.qb-next{border:1px solid var(--qb-border);border-radius:12px;min-height:104px;padding:15px;display:flex;align-items:center;gap:14px}
.qb-next-main{flex:1;min-width:0}.qb-next-main strong{display:block;font-size:.95rem}.qb-next-main span{display:block;margin-top:7px;color:var(--qb-muted);font-size:.84rem}
.qb-meta{border-top:1px solid var(--qb-border);display:grid;grid-template-columns:repeat(4,minmax(0,1fr));padding-top:16px;gap:0}
.qb-meta-item{padding:0 16px;min-width:0;border-inline-start:1px solid var(--qb-border);display:flex;align-items:center;gap:12px}.qb-meta-item:first-child{border:0;padding-inline-start:0}
.qb-meta-item svg{width:22px;height:22px;flex:none;color:var(--qb-blue)}.qb-meta-item dt{font-size:.78rem;color:var(--qb-muted)}.qb-meta-item dd{font-size:.85rem;color:var(--qb-text);margin:6px 0 0;overflow-wrap:anywhere}
.qb-disclosure>summary{display:flex;align-items:center;cursor:pointer;list-style:none;padding:18px 20px;gap:12px}.qb-disclosure>summary::-webkit-details-marker{display:none}.qb-disclosure>summary .qb-chevron{margin-inline-start:auto;width:18px;height:18px;color:var(--qb-blue);transition:transform .15s}.qb-disclosure[open]>summary .qb-chevron{transform:rotate(180deg)}.qb-disclosure-body{padding:0 20px 18px}
.qb-technical-title{display:block;font-size:1.1rem;font-weight:750}.qb-technical-help{font-size:.79rem;color:var(--qb-muted);display:block;margin-top:3px}
.qb-issue-grid{display:grid;grid-template-columns:1.9fr 1.1fr;gap:14px}
.qb-issue-list{display:grid;gap:6px}.qb-issue-row{display:flex;align-items:center;gap:12px;border:1px solid var(--qb-border);border-radius:9px;padding:10px 12px;min-width:0}.qb-issue-text{min-width:0;flex:1}.qb-issue-text strong{display:block;font-size:.89rem}.qb-issue-text small{display:block;color:var(--qb-muted);font-size:.76rem;margin-top:3px;line-height:1.35}.qb-issue-row .qb-pill{margin-inline-start:auto}.qb-issue-row .qb-chevron{width:17px;height:17px;color:var(--qb-blue)}
.qb-checks{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.qb-check{border:1px solid var(--qb-border);border-radius:10px;padding:13px;min-width:0;display:flex;flex-direction:column;align-items:flex-start;min-height:150px}.qb-check-top{display:flex;align-items:center;gap:9px;width:100%}.qb-check-top strong{font-size:.9rem;line-height:1.25}.qb-check .qb-pill{margin-top:8px}.qb-check p{color:var(--qb-muted);font-size:.77rem;margin:8px 0 0;line-height:1.35}.qb-detail-link{margin-top:auto;padding-top:10px;color:var(--qb-blue);font-size:.78rem;font-weight:700;text-decoration:none;cursor:pointer}
.qb-kv{display:grid;gap:0}.qb-kv-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:6px 4px;border-bottom:1px solid var(--qb-border);font-size:.83rem}.qb-kv-row:last-child{border-bottom:0}.qb-kv-row .qb-kv-label{display:flex;align-items:center;gap:9px;min-width:0}.qb-kv-row svg{width:18px;height:18px;color:var(--qb-blue);flex:none}.qb-kv-row bdi{color:var(--qb-muted);text-align:end;overflow-wrap:anywhere}
.qb-accordion{display:grid;gap:0}.qb-accordion details{border:1px solid var(--qb-border);border-radius:8px;margin-top:-1px;min-width:0}.qb-accordion summary{list-style:none;display:flex;align-items:center;justify-content:space-between;padding:8px 14px;cursor:pointer;font-size:.86rem;font-weight:700}.qb-accordion summary::-webkit-details-marker{display:none}.qb-accordion summary svg{width:17px;height:17px;color:var(--qb-blue)}.qb-accordion details[open] summary svg{transform:rotate(180deg)}.qb-accordion-content{border-top:1px solid var(--qb-border);padding:13px 15px;font-size:.82rem;color:var(--qb-muted);line-height:1.6;overflow-wrap:anywhere}.qb-accordion-content p{margin:5px 0}
.qb-stepper{padding:18px 30px;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));position:relative;gap:10px}.qb-stepper:before{content:"";position:absolute;top:37px;inset-inline:12%;border-top:1px dashed var(--qb-border)}.qb-step{position:relative;z-index:1;text-align:center;min-width:0}.qb-step-icon{width:42px;height:42px;border-radius:50%;margin:0 auto 9px;display:flex;align-items:center;justify-content:center;background:var(--qb-card);border:2px solid var(--qb-border);color:var(--qb-muted)}.qb-step-icon svg{width:20px;height:20px}.qb-step.is-complete .qb-step-icon{border-color:var(--qb-green);color:var(--qb-green)}.qb-step.is-current .qb-step-icon{border-color:var(--qb-blue);color:var(--qb-blue);box-shadow:0 0 0 4px color-mix(in srgb,var(--qb-blue) 13%,transparent)}.qb-step strong{display:block;font-size:.88rem}.qb-step small{display:block;font-size:.76rem;color:var(--qb-muted);margin-top:4px}
.qb-select-grid{border:1px solid var(--qb-border);border-radius:10px;padding:14px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.qb-field{min-width:0}.qb-field label{display:flex;align-items:center;gap:7px;font-weight:700;font-size:.88rem;margin-bottom:9px}.qb-field label svg{width:18px;height:18px;color:var(--qb-blue)}.qb-field select{width:100%;background:var(--qb-card-2);border:1px solid var(--qb-border);color:var(--qb-text);border-radius:8px;min-height:42px;padding:7px 12px}.qb-field small{display:block;margin-top:7px;color:var(--qb-muted);font-size:.76rem}.qb-form-actions{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-top:13px}.qb-primary-button{border:0;background:#216df3;color:#fff;border-radius:8px;padding:9px 17px;font-weight:700;cursor:pointer}.qb-primary-button:disabled{opacity:.5;cursor:not-allowed}.qb-form-status{font-size:.82rem;color:var(--qb-muted)}
.qb-restore-result{grid-template-columns:minmax(0,1fr) 230px;min-height:280px;align-items:start}.qb-restore-result .qb-hero-art{height:180px;align-self:center}.qb-restore-result .qb-hero-main>p{margin-top:6px}.qb-success-notice{border:1px solid var(--qb-green);background:var(--qb-green-soft);border-radius:8px;padding:12px 15px;margin-top:16px;color:var(--qb-green);font-size:.86rem;line-height:1.5}.qb-success-notice strong{display:block}.qb-success-notice small{color:var(--qb-muted);display:block;margin-top:4px}
.qb-restore-result .qb-info-wrap{grid-row:2}
.qb-overview .qb-columns> :first-child,.qb-health .qb-columns> :first-child{order:2}
.qb-info-wrap{grid-column:1/-1;border:1px solid var(--qb-border);border-radius:10px;padding:12px}.qb-info-title{font-size:.82rem;font-weight:700;margin:0 0 10px}.qb-info-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px}.qb-info-tile{border:1px solid var(--qb-border);border-radius:8px;padding:10px;min-width:0;font-size:.76rem}.qb-info-tile span{display:block;color:var(--qb-muted);margin-bottom:7px}.qb-info-tile bdi{display:block;color:var(--qb-text);font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.qb-guidance{display:grid;gap:5px}.qb-guidance-item{border:1px solid var(--qb-border);border-radius:8px;padding:7px;display:flex;align-items:center;gap:9px;min-width:0}.qb-guidance-number{width:30px;height:30px;border:1px solid var(--qb-blue);border-radius:50%;display:grid;place-items:center;color:var(--qb-blue);background:var(--qb-blue-soft);font-size:.8rem;flex:none}.qb-guidance-item strong{font-size:.79rem;line-height:1.35}.qb-guidance-item .qb-icon{margin-inline-start:auto;width:30px;height:30px}.qb-guidance-item .qb-icon svg{width:17px;height:17px}
.qb-timeline{display:grid;gap:0}.qb-timeline-item{display:grid;grid-template-columns:minmax(0,1fr) 13px 90px;gap:12px;min-height:74px;align-items:start;border-bottom:1px solid var(--qb-border);padding:9px 0}.qb-timeline-item:last-child{border:0}.qb-timeline-main strong{font-size:.85rem}.qb-timeline-main small{display:block;color:var(--qb-muted);font-size:.75rem;margin-top:4px;line-height:1.4}.qb-timeline-main .qb-pill{margin-inline-start:7px}.qb-timeline-line{position:relative;height:100%}.qb-timeline-line:before{content:"";position:absolute;left:6px;top:0;bottom:-10px;border-left:1px solid var(--qb-border)}.qb-timeline-item:last-child .qb-timeline-line:before{bottom:50%}.qb-timeline-line:after{content:"";position:absolute;left:1px;top:10px;width:11px;height:11px;border-radius:50%;background:var(--qb-blue);box-shadow:0 0 0 3px var(--qb-blue-soft)}.qb-timeline-item.is-success .qb-timeline-line:after{background:var(--qb-green)}.qb-timeline-item.is-failed .qb-timeline-line:after{background:var(--qb-red)}.qb-timeline-time{font-size:.78rem;text-align:start;direction:ltr;color:var(--qb-muted)}
.qb-truncate{max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;direction:ltr}.qb-warn-text{color:var(--qb-amber)}.qb-success-text{color:var(--qb-green)}.qb-danger-text{color:var(--qb-red)}
@media(max-width:1200px){.qb-hero{grid-template-columns:150px minmax(0,1fr)}.qb-info-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.qb-checks{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:900px){.qb-design.fi-page{padding:16px}.qb-issue-grid,.qb-columns{grid-template-columns:1fr}.qb-meta{grid-template-columns:repeat(2,minmax(0,1fr));row-gap:16px}.qb-meta-item:nth-child(3){border:0;padding-inline-start:0}.qb-health .qb-hero{grid-template-columns:minmax(0,1fr) 130px}.qb-health .qb-hero-art{grid-column:2}.qb-health .qb-hero-main{grid-column:1}.qb-health-rail{grid-column:1/-1;grid-row:2;display:flex;border:0;border-top:1px solid var(--qb-border);padding:10px 0 0;gap:20px}.qb-health-rail>div{border:0;padding:0}}
@media(max-width:768px){.qb-design .fi-header{align-items:flex-start}.qb-summary-grid{grid-template-columns:1fr}.qb-hero,.qb-restore-result,.qb-health .qb-hero{grid-template-columns:1fr;gap:8px}.qb-hero-art,.qb-health .qb-hero-art{height:100px;grid-column:1;grid-row:1}.qb-hero-art svg{width:70px;height:70px}.qb-hero-main,.qb-health .qb-hero-main{grid-column:1;grid-row:2}.qb-restore-result .qb-info-wrap{grid-column:1;grid-row:3}.qb-health-rail{grid-column:1;grid-row:3;flex-wrap:wrap}.qb-select-grid{grid-template-columns:1fr}.qb-info-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.qb-stepper{padding:15px 8px}.qb-step strong{font-size:.74rem}.qb-step small{font-size:.67rem}.qb-step-icon{width:34px;height:34px}.qb-stepper:before{top:32px}.qb-timeline-item{grid-template-columns:minmax(0,1fr) 13px 70px}}
@media(max-width:500px){.qb-checks,.qb-meta,.qb-info-grid{grid-template-columns:1fr}.qb-meta-item{border:0;padding:0}.qb-section{padding:15px}.qb-step small{display:none}.qb-issue-row{flex-wrap:wrap}.qb-issue-row .qb-pill{margin-inline-start:0}.qb-timeline-item{grid-template-columns:minmax(0,1fr) 13px 56px;gap:6px}}
</style>
